### ISSUE TITLE
js 引入是这样使用吗?方便给一个js的例子吗

### ISSUE THREAD

**Issue by tzhanhe** [hcfw007/nw-vue-horizontal-tree#1]
<head>
    <meta charset='utf-8'>
    <script type="text/javascript" src="https://unpkg.com/vue"></script>
    
    <script type="text/javascript" src="./js/tree.global.js"></script>

    <style>
     
    </style>		
</head>
<dev id="app">
<tree-node :tree-data="treeData" />
</dev>
<script type="text/javascript">
let treeData = {
    name: 'root',
    children: [{
        name: 'child1',
        children: [{
            name: 'child1-1',
            children: [],
        }, {
            name: 'child1-2',
            children: [],
        }],
    }, {
        name: 'child2',
        children: [],
    }],
};
    let vm = new Vue({
        el: '#app',
        data: treeData
		})
</script>

**Comment by hcfw007** [comment]
好的，我弄一个一会儿放上来。第一次有人给我发issue好感动。

**Comment by tzhanhe** [comment]
Thank you.
